resolver: lts-23.19
packages:
- vcard
- vcard-gen

# These are duplicated in nix/overlay.nix
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wunused-packages

extra-deps:
- conformance-gen-0.0.0.0@sha256:7d98b5a0f5b68bb20e13fb7d6830c0e0c59f1778e4d1c74a3075bab0fad47542,978

system-ghc: true
nix:
  enable: false
with-hpack: hpack
