name: vcard-gen
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - bytestring
  - case-insensitive
  - conformance
  - conformance-gen
  - dlist
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-case-insensitive
  - genvalidity-containers
  - genvalidity-network-uri
  - genvalidity-network-uri
  - genvalidity-sydtest
  - genvalidity-text
  - genvalidity-time
  - path
  - sydtest
  - text
  - vcard

benchmarks:
  vcard-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - criterion
    - genvalidity-criterion
    - genvalidity-vector
    - vcard
    - vcard-gen

tests:
  vcard-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - bytestring
    - conformance
    - conformance-gen
    - dlist
    - genvalidity-sydtest
    - genvalidity-text
    - megaparsec
    - path
    - sydtest
    - text
    - time
    - vcard
    - vcard-gen
